---
kind: pipeline
type: docker
name: default

steps:
  - name: subversion
    image: pikado/alpine-svn
    environment:
      SVNSECRET:
        from_secret: svn_secret
    commands:
      - svn co --username $SVNSECRET --password $SVNSECRET http://hermes.interactive-instruments.de/svn/test/trunk/neuesprojekt/

  - name: cmake
    image: lycantropos/cmake
    commands:
      - cmake .