pipeline:

  build:
    image: docker.ci.interactive-instruments.de/cicd/debian-buster-gcc83
    commands:
      - cmake .
      - cmake --build .
      - ./citest

  test:
    image: plugins/webhook
    settings:
      urls: http://xtf-200:8080/job/Packaging_Trigger_Helper/buildWithParameters?trigger=citesting&project=abc&svnpath=xyzpath&token=token
