---
kind: pipeline
type: docker
name: default

steps:
  - name: subversion
    image: pikado/alpine-svn
    commands:
      - svn co http://hermes.interactive-instruments.de/svn/test/trunk/neuesprojekt/
